name: autofix.ci

on: 
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  autofix:
    name: AutoFix.CI
    runs-on: ubuntu-latest

    steps:
    - name: Load Repository
      uses: actions/checkout@v4
      
    - name: Load Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Continous Integration
      run: |
        bun install
        bun run format
        bun run lint
        bun run build

    - name: Commit
      uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc